{
  "formatVersion": "1.1",
  "component": {
    "group": "com.allinteck.stack",
    "module": "bind-processor",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bind-processor-1.0.0.jar",
          "url": "bind-processor-1.0.0.jar",
          "size": 5820,
          "sha512": "9eda4047054dc3a5bf224dd3c2ef138d9f31157fca634af2c93b35444ff9aca4578b9cebd1d747e86c03a2c36d1f1d55f6123d60d123ee3ab246ede27cfd994b",
          "sha256": "8cde5ebb00cf1638ac707057ac6a07df763816a20bd323d5133fe151a5f1db02",
          "sha1": "a02496682c864bc0b79c8df80a7320a90f11e9a2",
          "md5": "bd5846d3f6adc8d3f1385392a1a7461e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.allinteck.stack",
          "module": "bind-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        }
      ],
      "files": [
        {
          "name": "bind-processor-1.0.0.jar",
          "url": "bind-processor-1.0.0.jar",
          "size": 5820,
          "sha512": "9eda4047054dc3a5bf224dd3c2ef138d9f31157fca634af2c93b35444ff9aca4578b9cebd1d747e86c03a2c36d1f1d55f6123d60d123ee3ab246ede27cfd994b",
          "sha256": "8cde5ebb00cf1638ac707057ac6a07df763816a20bd323d5133fe151a5f1db02",
          "sha1": "a02496682c864bc0b79c8df80a7320a90f11e9a2",
          "md5": "bd5846d3f6adc8d3f1385392a1a7461e"
        }
      ]
    }
  ]
}
