{
  "formatVersion": "1.1",
  "component": {
    "group": "com.luojilab.ddcomponentx",
    "module": "router-annotation",
    "version": "1.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-annotation-1.5.0.jar",
          "url": "router-annotation-1.5.0.jar",
          "size": 6458,
          "sha512": "4fa97b5e119c2e8ef97c43546daf870299549661159087c2afe85e9863eb3c0aaaf614bcf7d9792293304aa429597e4015df41fc342d2bb5f71ebb5510c0321e",
          "sha256": "f0aa4da78760b3ad49ff3af52646f9e6c754b99c8f580b0cb5f6ea5f3ee46c6f",
          "sha1": "b4b98e938ec30f7f4ba8bdf1d4d79299a6ffbc14",
          "md5": "0493360931cc3bcd065dce2da972be67"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "router-annotation-1.5.0.jar",
          "url": "router-annotation-1.5.0.jar",
          "size": 6458,
          "sha512": "4fa97b5e119c2e8ef97c43546daf870299549661159087c2afe85e9863eb3c0aaaf614bcf7d9792293304aa429597e4015df41fc342d2bb5f71ebb5510c0321e",
          "sha256": "f0aa4da78760b3ad49ff3af52646f9e6c754b99c8f580b0cb5f6ea5f3ee46c6f",
          "sha1": "b4b98e938ec30f7f4ba8bdf1d4d79299a6ffbc14",
          "md5": "0493360931cc3bcd065dce2da972be67"
        }
      ]
    }
  ]
}
