{
  "formatVersion": "1.1",
  "component": {
    "group": "com.luojilab.ddcomponentx",
    "module": "router-anno-compiler",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-anno-compiler-1.5.1.jar",
          "url": "router-anno-compiler-1.5.1.jar",
          "size": 22135,
          "sha512": "8eb323abb8b5b71c8d203a4ec246f8f6846c878f89ec365cef6aa48cf54d0a8f656c110b09451cb5206820d79b863d1bcfb979ec2001a047ec79bec03274bb53",
          "sha256": "4b3ec8b4dd54d2dcd34bc4e7ced44ae7c95d5e7ea766930a60465df8d18ee7a0",
          "sha1": "f3573163610266ce071a209162ccb6a416f8e8ad",
          "md5": "6425dd7c85bb72022e40cd75a037197d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "com.luojilab.ddcomponentx",
          "module": "router-annotation",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "router-anno-compiler-1.5.1.jar",
          "url": "router-anno-compiler-1.5.1.jar",
          "size": 22135,
          "sha512": "8eb323abb8b5b71c8d203a4ec246f8f6846c878f89ec365cef6aa48cf54d0a8f656c110b09451cb5206820d79b863d1bcfb979ec2001a047ec79bec03274bb53",
          "sha256": "4b3ec8b4dd54d2dcd34bc4e7ced44ae7c95d5e7ea766930a60465df8d18ee7a0",
          "sha1": "f3573163610266ce071a209162ccb6a416f8e8ad",
          "md5": "6425dd7c85bb72022e40cd75a037197d"
        }
      ]
    }
  ]
}
