{
  "formatVersion": "1.1",
  "component": {
    "group": "com.allinteck.stack",
    "module": "bind-processor",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bind-processor-1.0.1.jar",
          "url": "bind-processor-1.0.1.jar",
          "size": 5821,
          "sha512": "4676c006b110ee1cace1b7799545fc91f862ec093cf6f31ec50c9cfa0d1c9670f515cc432208442dd95f616ab7b8e6556779cb2ec01e941bfee20b43875fc050",
          "sha256": "f4caf9ebbad857bb632ee41d91fb4af7f119b32efff1dd2793b1b525ada8805b",
          "sha1": "4d262beb18ea5ee525347ca61f8fec0db418c9a0",
          "md5": "eccf0bf223b61bd08891e93a05ffe8de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.allinteck.stack",
          "module": "bind-annotation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc6"
          }
        }
      ],
      "files": [
        {
          "name": "bind-processor-1.0.1.jar",
          "url": "bind-processor-1.0.1.jar",
          "size": 5821,
          "sha512": "4676c006b110ee1cace1b7799545fc91f862ec093cf6f31ec50c9cfa0d1c9670f515cc432208442dd95f616ab7b8e6556779cb2ec01e941bfee20b43875fc050",
          "sha256": "f4caf9ebbad857bb632ee41d91fb4af7f119b32efff1dd2793b1b525ada8805b",
          "sha1": "4d262beb18ea5ee525347ca61f8fec0db418c9a0",
          "md5": "eccf0bf223b61bd08891e93a05ffe8de"
        }
      ]
    }
  ]
}
