{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tangzy.stack",
    "module": "bind-library",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bind-library-1.0.1.aar",
          "url": "bind-library-1.0.1.aar",
          "size": 2315,
          "sha512": "6309214dc5f6f21e46dfaf31557098f88a08ad1bbb225d86b788f1749401f3cda44c654d5519de9496b1b5b849b9109ecaf5a1b0a4fa9e4b7ac43cf6406b40d1",
          "sha256": "9392f40d4bcb1ff58af75957eed920d523f4f4c3400e084424592c2e39f2dbeb",
          "sha1": "5e345512d1a2dff9433a924bc31a38e32aa740fd",
          "md5": "e7b40f1905f6dccf6e642bcc8c416431"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bind-library-1.0.1.aar",
          "url": "bind-library-1.0.1.aar",
          "size": 2315,
          "sha512": "6309214dc5f6f21e46dfaf31557098f88a08ad1bbb225d86b788f1749401f3cda44c654d5519de9496b1b5b849b9109ecaf5a1b0a4fa9e4b7ac43cf6406b40d1",
          "sha256": "9392f40d4bcb1ff58af75957eed920d523f4f4c3400e084424592c2e39f2dbeb",
          "sha1": "5e345512d1a2dff9433a924bc31a38e32aa740fd",
          "md5": "e7b40f1905f6dccf6e642bcc8c416431"
        }
      ]
    }
  ]
}
