{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tangzy.plugin",
    "module": "gradleplugin",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradleplugin-1.0.2.jar",
          "url": "gradleplugin-1.0.2.jar",
          "size": 2683,
          "sha512": "c083ca025584644d472c9d04426620e9df5a8adea5063e01ba1dcd12c15bacc47629f02bd7928e658f84269d194352c9fb9793922ce78df216202e1b9e909ee2",
          "sha256": "93e4193b5f91387a49778f6b62afcab8de3b2322c547bd633147f41edda69086",
          "sha1": "a0c7826c978f583b4a248474679ffdebbb000eff",
          "md5": "4716914e4b9c61990f1ea07b3ecf3372"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradleplugin-1.0.2.jar",
          "url": "gradleplugin-1.0.2.jar",
          "size": 2683,
          "sha512": "c083ca025584644d472c9d04426620e9df5a8adea5063e01ba1dcd12c15bacc47629f02bd7928e658f84269d194352c9fb9793922ce78df216202e1b9e909ee2",
          "sha256": "93e4193b5f91387a49778f6b62afcab8de3b2322c547bd633147f41edda69086",
          "sha1": "a0c7826c978f583b4a248474679ffdebbb000eff",
          "md5": "4716914e4b9c61990f1ea07b3ecf3372"
        }
      ]
    }
  ]
}
