{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tangzy.plugin",
    "module": "gradleplugin",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradleplugin-1.0.2.jar",
          "url": "gradleplugin-1.0.2.jar",
          "size": 2509,
          "sha512": "3fc0411c90d502f22a8bec2b9437c1469ab2c19741c08a9d706d8925e1561af7b21965484e49673ae60132ca996f37cffe863b575413439e9fe4f2da88ea7d06",
          "sha256": "bee624d4bce1e0e58085c3de1eccb4acb6e007eb3ad3ca21724f9c9f1c954843",
          "sha1": "bbd9be30c68a6e18b1df69208ac1f6f8e9087fb7",
          "md5": "d723992b58d595edb95ac95fb24594c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gradleplugin-1.0.2.jar",
          "url": "gradleplugin-1.0.2.jar",
          "size": 2509,
          "sha512": "3fc0411c90d502f22a8bec2b9437c1469ab2c19741c08a9d706d8925e1561af7b21965484e49673ae60132ca996f37cffe863b575413439e9fe4f2da88ea7d06",
          "sha256": "bee624d4bce1e0e58085c3de1eccb4acb6e007eb3ad3ca21724f9c9f1c954843",
          "sha1": "bbd9be30c68a6e18b1df69208ac1f6f8e9087fb7",
          "md5": "d723992b58d595edb95ac95fb24594c5"
        }
      ]
    }
  ]
}
