{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tangzy.plugin",
    "module": "gradleplugin",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gradleplugin-1.0.2.jar",
          "url": "gradleplugin-1.0.2.jar",
          "size": 42154,
          "sha512": "e404cf45261171fa12c1485829a2af5a59732fe238b5ba0798ff7c62324b0344044f4cbd748c8517a72c466618b640a57769b3637187b6ecd4d90cd8cbad8135",
          "sha256": "4a4565d6eff76f03573dab97b5b3568b9ca5ef65bb9175e0c2158a06fcd7f4fc",
          "sha1": "50415e9d20a6c582e723bd84dccec2ee872116a0",
          "md5": "e4a5276234d573a0cdc6e776f7c30423"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.20.0-GA"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.0.1"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "transform-api",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "gradleplugin-1.0.2.jar",
          "url": "gradleplugin-1.0.2.jar",
          "size": 42154,
          "sha512": "e404cf45261171fa12c1485829a2af5a59732fe238b5ba0798ff7c62324b0344044f4cbd748c8517a72c466618b640a57769b3637187b6ecd4d90cd8cbad8135",
          "sha256": "4a4565d6eff76f03573dab97b5b3568b9ca5ef65bb9175e0c2158a06fcd7f4fc",
          "sha1": "50415e9d20a6c582e723bd84dccec2ee872116a0",
          "md5": "e4a5276234d573a0cdc6e776f7c30423"
        }
      ]
    }
  ]
}
