{
  "formatVersion": "1.1",
  "component": {
    "group": "com.allinteck.stack",
    "module": "bind-annotation",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bind-annotation-1.0.1.jar",
          "url": "bind-annotation-1.0.1.jar",
          "size": 977,
          "sha512": "84fc5ab6fce9227a4d425a2c53718e196e2290ef03c954933f5529ac9fcfaeb1e1075905f0c8ce1f4329dac56decb33b8646f6911694aad6aa1a551585c6b00a",
          "sha256": "d63c9756302392641a0f5eea4136f6a7ef53ddfe91526ae5fae2e90ee3d2fdc0",
          "sha1": "4873af4207988a545a0adc19aa5db024e81640b6",
          "md5": "f16ad7fec0af24ab05a53fa423ed3367"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bind-annotation-1.0.1.jar",
          "url": "bind-annotation-1.0.1.jar",
          "size": 977,
          "sha512": "84fc5ab6fce9227a4d425a2c53718e196e2290ef03c954933f5529ac9fcfaeb1e1075905f0c8ce1f4329dac56decb33b8646f6911694aad6aa1a551585c6b00a",
          "sha256": "d63c9756302392641a0f5eea4136f6a7ef53ddfe91526ae5fae2e90ee3d2fdc0",
          "sha1": "4873af4207988a545a0adc19aa5db024e81640b6",
          "md5": "f16ad7fec0af24ab05a53fa423ed3367"
        }
      ]
    }
  ]
}
