{
  "formatVersion": "1.1",
  "component": {
    "group": "com.luojilab.ddcomponentx",
    "module": "router-annotation",
    "version": "1.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-annotation-1.5.1.jar",
          "url": "router-annotation-1.5.1.jar",
          "size": 6458,
          "sha512": "b1488e969445d94f357d6348c3eec771a1054b16d13b0ffa34c97b48b3648062cd81d22dabf5cbb39b968543b9de49b4fdd53f2989e8b26193f218e35e7ecf55",
          "sha256": "b5dd5078aad354a8476f94378bc43a6bbd7d6b5fceb17809d543671b989e49c8",
          "sha1": "1ac876289781eca360bc8fd006835bcdbae70ed3",
          "md5": "70b80bacc89efb3eaf8b8a069d2a3e72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "router-annotation-1.5.1.jar",
          "url": "router-annotation-1.5.1.jar",
          "size": 6458,
          "sha512": "b1488e969445d94f357d6348c3eec771a1054b16d13b0ffa34c97b48b3648062cd81d22dabf5cbb39b968543b9de49b4fdd53f2989e8b26193f218e35e7ecf55",
          "sha256": "b5dd5078aad354a8476f94378bc43a6bbd7d6b5fceb17809d543671b989e49c8",
          "sha1": "1ac876289781eca360bc8fd006835bcdbae70ed3",
          "md5": "70b80bacc89efb3eaf8b8a069d2a3e72"
        }
      ]
    }
  ]
}
