{
  "formatVersion": "1.1",
  "component": {
    "group": "com.luojilab.ddcomponentx",
    "module": "router-anno-compiler",
    "version": "1.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "router-anno-compiler-1.5.2.jar",
          "url": "router-anno-compiler-1.5.2.jar",
          "size": 22224,
          "sha512": "8809dedc95af1d70c7bb699f7f49110186ae518767ffb58613bb7bc5e5bf3a05ce663428f2058e7f787111d8ecade8c53626b8d5b513d7cf6384cdaefda71818",
          "sha256": "8e319cd47dd6e3a84170f5128bf7296a294290018c4726beb37ad78b840d992b",
          "sha1": "83ccde122154e98dee0051db82466e8efb00f2e5",
          "md5": "28d4aa0bbc0869b706c41598b60d3550"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.auto.service",
          "module": "auto-service",
          "version": {
            "requires": "1.0-rc2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.1"
          }
        },
        {
          "group": "com.luojilab.ddcomponentx",
          "module": "router-annotation",
          "version": {
            "requires": "1.5.1"
          }
        }
      ],
      "files": [
        {
          "name": "router-anno-compiler-1.5.2.jar",
          "url": "router-anno-compiler-1.5.2.jar",
          "size": 22224,
          "sha512": "8809dedc95af1d70c7bb699f7f49110186ae518767ffb58613bb7bc5e5bf3a05ce663428f2058e7f787111d8ecade8c53626b8d5b513d7cf6384cdaefda71818",
          "sha256": "8e319cd47dd6e3a84170f5128bf7296a294290018c4726beb37ad78b840d992b",
          "sha1": "83ccde122154e98dee0051db82466e8efb00f2e5",
          "md5": "28d4aa0bbc0869b706c41598b60d3550"
        }
      ]
    }
  ]
}
